version: "3"

services:
  postgres:
    container_name: postgres
    image: postgres:12
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
      - ./db/db_init.sql:/docker-entrypoint-initdb.d/0.init.sql
      - ./db/tests/test_data.sql:/docker-entrypoint-initdb.d/1.test_data.sql
    ports:
      - "5432:5432"
    networks:
      - rnotes
    restart: unless-stopped

networks:
  rnotes:
    driver: bridge

volumes:
  postgres:
