version: "3"

services:
  postgres:
    container_name: postgres
    image: postgres:12
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
      - ./db/db_init.sql:/docker-entrypoint-initdb.d/0.init.sql
      - ./db/db_default_data.sql:/docker-entrypoint-initdb.d/1.default_data.sql
    ports:
      - "5432:5432"
    networks:
      - rnotes
    restart: unless-stopped

  rnotes:
    container_name: rnotes
    image: rnotes
    environment:
      DATABASE_URL: "postgres://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-postgres}@postgres/postgres"
      DATABASE_SCHEMA: "rnotes"
      ROCKET_ADDRESS: "localhost"
      ROCKET_PORT: "8080"
      JWT_SECRET_KEY: "some_secret_key"
      JWT_SESSION_TIME: "3600"
    ports:
      - "${RNOTES_PORT:-8080}:8080"
    networks:
      - rnotes
    restart: unless-stopped

networks:
  rnotes:
    driver: bridge

volumes:
  postgres:
